[package]
name = "fater"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.105"
web-sys = { version = "0.3.82", features   = ['Document', 'Element', 'HtmlElement', 'Node', 'Window']}
